import type { Metadata } from "next";
import { Footer } from "../../components/blocks/footer";
import { Navbar } from "../../components/blocks/navbar";
import { Breadcrumb } from "../../components/blocks/breadcrumb";
import { Taglist } from "../../components/blocks/taglist";
import { LandingResults } from "../../components/landing-results";
// CUSTOM DATA
import data from "../../data/landing";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
export default function Landing() {
    return (
<>

    <Navbar/>      

    <Breadcrumb items={data.breadcrumb} />


  <section className="wrapper bg-light">
    <div className="container pt-8 pt-md-10">
      <div className="row align-items-center mb-10 position-relative zindex-1">
        <div className="col-12 pe-xl-20">
          <h1 className="display-2 mb-0">
            Las mejores Peluquerías cerca de mi en Santiago
          </h1>
        </div>
        
        <Taglist items={data.taglist} />

      </div>
    </div>
  </section>  

  <LandingResults items={data.breadcrumb} />
      
  <section className="wrapper bg-light wrapper-border">
    <div className="container py-11">
      <h2 className="h5">¡Descubre otros servicios en Santiago!</h2>
      <ul className="list-inline mb-0">
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/barberias-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Barbería
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/centros-de-medicina-alternativa-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Medicina Alternativa
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/centros-deportivos-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Centro Deportivo
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/centros-estetica-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Centro de Estética
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/centros-kinesiologicos-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Kinesiólogo / Fisioterapeuta
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/centros-medicos-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Centro Médico
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/centros-psicologicos-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Psicólogo
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/clinicas-odontologicas-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Clínica Odontológica
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/clinicas-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Clínica
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/consultas-medicas-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Consulta Médica
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/estilistas-independientes-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Estilista Independiente
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/gimnasios-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Gimnasio
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/peluquerias-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Peluquería
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/salones-belleza-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Salón de Belleza
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/salones-cejas-pestanas-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Salón de Cejas y Pestañas
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/salones-manicure-pedicure-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Salón de Manicure y Pedicure
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/spas-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Spa
          </a>
        </li>
        <li className="list-inline-item me-1 mb-2">
          <a
            href="/mp/cl/veterinarias-santiago"
            className="btn btn-soft-ash btn-sm rounded-pill"
          >
            Veterinaria
          </a>
        </li>
      </ul>
    </div>
    {/* /.container */}
  </section>
  <section className="wrapper bg-light">
    <div className="container px-10 py-12 py-md-12 mt-14 mb-14 bg-soft-ash rounded">
      <div className="row gx-lg-8 gx-xl-12 gy-10 align-items-center">
        <div className="col-lg-7 position-relative">
          <div className="row">
            <img
              loading="lazy"
              src="/web_assets/img/AgendaPro_cta_market.webp"
            />
          </div>
        </div>
        {/*/column */}
        <div className="col-lg-5">
          <p className="display-1 fs-40 mb-4 text-dark">
            Crea tu agenda online y comienza a recibir citas
          </p>
          <p className="mb-5 text-dark">
            Ahorra tiempo y maximiza la eficiencia con nuestras poderosas
            herramientas de gestión. Descubre cómo nuestro
            <a
              className="link-dark"
              href="https://agendapro.com/cl/peluqueria/software-para-peluquerias"
            >
              Software para Peluquerías
            </a>
            puede potenciar tu negocio hoy mismo.
          </p>
          <div className="d-flex justify-content-center justify-content-lg-start">
            <span>
              <a
                href="https://agendapro.com/lead/market/signup"
                className="btn btn-orange rounded btn-apsignup"
                title="Regístrate en AgendaPro"
              >
                Descubre más
              </a>
            </span>
          </div>
        </div>
        {/*/column */}
      </div>
      {/*/.row */}
    </div>
  </section>
  <section className="wrapper links-section mt-0 mb-14">
    <div className="container">
      <div className="row gy-6 gy-lg-0 mt-0 mb-0">
        <span className="fs-20 text-dark mb-6">
          También puedes encontrar Peluquerías en:
        </span>
        <div className="col-md-12 col-lg-12 links-columns mb-4"></div>
        {/* /column */}
        <div className="col-md-12 col-lg-12 links-columns">
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-buin">
            Peluquerías en Buin
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-cerrillos"
          >
            Peluquerías en Cerrillos
          </a>
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-colina">
            Peluquerías en Colina
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-conchali"
          >
            Peluquerías en Conchalí
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-estacion-central"
          >
            Peluquerías en Estación Central
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-huechuraba"
          >
            Peluquerías en Huechuraba
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-independencia"
          >
            Peluquerías en Independencia
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-isla-de-maipo"
          >
            Peluquerías en Isla de Maipo
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-la-cisterna"
          >
            Peluquerías en La Cisterna
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-la-florida"
          >
            Peluquerías en La Florida
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-la-pintana"
          >
            Peluquerías en La Pintana
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-la-reina"
          >
            Peluquerías en La Reina
          </a>
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-lampa">
            Peluquerías en Lampa
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-las-condes"
          >
            Peluquerías en Las Condes
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-lo-barnechea"
          >
            Peluquerías en Lo Barnechea
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-lo-prado"
          >
            Peluquerías en Lo Prado
          </a>
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-maipu">
            Peluquerías en Maipú
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-melipilla"
          >
            Peluquerías en Melipilla
          </a>
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-nunoa">
            Peluquerías en Ñuñoa
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-padre-hurtado"
          >
            Peluquerías en Padre Hurtado
          </a>
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-paine">
            Peluquerías en Paine
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-penaflor"
          >
            Peluquerías en Peñaflor
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-penalolen"
          >
            Peluquerías en Peñalolén
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-providencia"
          >
            Peluquerías en Providencia
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-pudahuel"
          >
            Peluquerías en Pudahuel
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-puente-alto"
          >
            Peluquerías en Puente Alto
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-quilicura"
          >
            Peluquerías en Quilicura
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-recoleta"
          >
            Peluquerías en Recoleta
          </a>
          <a className="me-6 text-reset fs-15" href="/mp/cl/peluquerias-renca">
            Peluquerías en Renca
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-san-bernardo"
          >
            Peluquerías en San Bernardo
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-san-miguel"
          >
            Peluquerías en San Miguel
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-santiago"
          >
            Peluquerías en Santiago
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-talagante"
          >
            Peluquerías en Talagante
          </a>
          <a
            className="me-6 text-reset fs-15"
            href="/mp/cl/peluquerias-vitacura"
          >
            Peluquerías en Vitacura
          </a>
        </div>
        {/* /column */}
      </div>
      {/*/.row */}
    </div>
  </section>



        <Footer/>
    </>
  );
}