import type { Metadata } from "next";
import { Footer } from "../../components/blocks/footer";
import { Navbar } from "../../components/blocks/navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
export default function CareerTwo() {
    return (
    <>
        <Navbar/>       
        <Footer/>
    </>
  );
}